### PR TITLE
Add tests for creating mappings and using feedkeys

### PR DESCRIPTION
**Pull request by joshaw**

### CODE REVIEW

**Comment by martanne** [comment]
I'm quite busy these days and still haven't yet had time to properly look at the test cases ...

For now I just wanted to see what kind of values are returned for the cases where you added an `or true` clause. This turned out to be more tedious than it should be. I'm still not really happy how the test are run.

Have you thought of changing `test.sh` to invoke vis as follows:

```
$VIS "$t".in > "$t".out
```

That way you could generate the desired output via `print(...)` from Lua. A test would then look more like:

``` lua
print("Test moving cursor to invalid position beyond EOF:")
win.cursor:to(1000, 1000)
print("line: " .. win.cursor.line)
print("col: " .. win.cursor.col)
print("pos: " .. win.cursor.pos)
```

The last 3 lines could of course also be moved to some kind of utility function. The expected values would be added to the corresponding `*.ref` file. That way looking at the test `*.out` and/or `*.err` file would suffice to know which test failed and what the wrong values were.

**Comment by joshaw** [comment]
Yeah, I agree that it's not as simple to debug as it could be.
I hadn't thought of just using `print()`, I guess the tui is all writtent to stderr? Using that method would make it more difficult to modify the buffer or file contents and then compare that, as it would be overwritten by the `> "$t.out"`.

I'm happy to rewrite tests, it's best to get it right now while there are so few. I appreciate you're busy; if you've got any thoughts, let  me know,  in the mean time I'll do some playing and try some things out.

**Comment by martanne** [comment]
> I guess the tui is all writtent to stderr?

Yes

> Using that method would make it more difficult to modify the buffer or file contents and then compare that, as it would be overwritten by the > "$t.out".

Have you tried it? I don't think this is the case, the shell will `truncate(2)` the file, then when writing a file with `:w` vis will `rename(2)` a new file over it.

**Comment by joshaw** [comment]
> I don't think this is the case, the shell will truncate(2) the file, then when writing a file with :w vis will rename(2) a new file over it.

That doesn't seem to be the case. I may be wrong, but if I change the execution command in test.sh to `$VIS "$t".in >"$t.out"` and add a `print(...)` to a test, I always get the contents of the print statement in the file, not the buffer contents saved by vis.

**Comment by martanne** [comment]
With typical Unix semantics it works as I described. However this apparently does not apply to Cygwin because Windows does not let you unlink/rename a file which is currently opened.

Hence if we want to be portable we should probably not depend on this behavior. We could let the tests write to another file and then once `vis` has terminated rename it to `*.out`

``` sh
$VIS "$t.in" > "$t.out"
[ -e "$t.write" ] && mv "$t.write" "$t.out"
```

Maybe there are better ways to do it ...

**Pull request merged**
